name: Deploy to EC2 using Ansible

on:
  repository_dispatch:
    types: [ trigger-cd ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: Package
          path: build/libs

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy artifact to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa build/libs ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/my-project

      - name: Run Ansible playbook
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'ansible-playbook /path/to/your/playbook.yml'