name: CI

# master branch 에 push / PR 이 일어날 때를 트리거로 하여 해당 build event 발생
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  # 작업 이름 build 정의
  build:
    # ubuntu 최신 이미지 위에서 실행
    runs-on: ubuntu-latest
    # 깃허브의 해당 작업에 대한 권한 범위
    permissions:
      # 해당 커밋에 대한 "읽기" 권한 있음.
      contents: read

    # 빌드 작업의 단계들.. '-' 가 Step 1, 2, 3 으로 관리될거임
    steps:
      # 레포로 체크아웃
      - uses: actions/checkout@v4
      # jdk 17 세팅 작업이라고 이름을 지정하고, uses 를 사용해 setup-java 함
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          # 궁금해서 찾아봤는데 JDK 이미지가 저장된 저장소 이름임..
          distribution: 'temurin'

      # Gradle 세팅, 아래 링크에 액션의 자세한 내용이 담겨있다.
      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      # build 명령
      - name: Build with Gradle Wrapper
        run: ./gradlew build

      # 아티팩트 업로드
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: build/libs/*.jar

  deploy:
    needs: build

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: build/libs
      - run: ls -R build/libs

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy artifact to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa build/libs ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/my-project

      - name: Run Ansible playbook
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'ansible-playbook /path/to/your/playbook.yml'

